#!/bin/bash

echo "🚂 Railway Database Connection Helper"
echo "====================================="
echo ""
echo "To connect to your Railway database from your local machine, you need:"
echo ""
echo "1. Go to your Railway dashboard: https://railway.app/dashboard"
echo "2. Click on your PostgreSQL service"
echo "3. Go to the 'Connect' tab"
echo "4. Look for 'Connect from external application'"
echo "5. Copy the connection details (they look like this):"
echo ""
echo "   Host: viaduct.proxy.rlwy.net"
echo "   Port: 12345"
echo "   Database: your-db-name"
echo "   Username: postgres"
echo "   Password: your-password"
echo ""
echo "⚠️  IMPORTANT: Do NOT use 'postgres.railway.internal' - that only works inside Railway!"
echo "   Use the external hostname (usually viaduct.proxy.rlwy.net)"
echo ""
echo "Once you have the external connection details, run:"
echo "   ./setup_database.sh"
echo ""
echo "Or manually set your DATABASE_URL environment variable:"
echo "   export DATABASE_URL='postgresql://username:password@external-host:port/database'"
echo ""
echo "Need help? Check Railway's documentation on external connections."
